/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;


import com.google.common.reflect.TypeToken;
import com.google.gson.Gson;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.lang.reflect.Type;
import java.util.List;


public class App {


    public static void main(String[] args){
        String path = "./app/src/main/resources/recentquotes.json";
        getQuote(path);
    }
    public static List getQuote(String path) {
        Gson gson = new Gson();
        FileReader fileReader = null;
        try {
            fileReader = new FileReader(path);
        } catch (FileNotFoundException e) {
            e.printStackTrace();
            System.out.println("Error");
        }
        Type quoteType = new TypeToken<List<Quotes>>(){}.getType();
        List<Quotes> allQuotes = gson.fromJson(fileReader, quoteType);
        int random = (int)(Math.random() * allQuotes.size());
        System.out.println(allQuotes.get(random).toString());

        return allQuotes;
    }
}